prometheus:
  nodeSelector:
    monitoring: enabled
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"      # 👈 must match the taint
      effect: "NoSchedule"

grafana:
  nodeSelector:
    monitoring: enabled
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"      # 👈 same here
      effect: "NoSchedule"

prometheusOperator:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

alertmanager:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
