# values-monitoring.yaml
prometheus:
  nodeSelector:
    monitoring: enabled
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "enabled"
      effect: "NoSchedule"

grafana:
  nodeSelector:
    monitoring: enabled
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "enabled"
      effect: "NoSchedule"
