apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: wait-for-auth
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup auth-service.microservices.svc.cluster.local; do
                echo "Waiting for auth-service..."
                sleep 2
              done
        - name: wait-for-order
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup order-service.microservices.svc.cluster.local; do
                echo "Waiting for order-service..."
                sleep 2
              done
        - name: wait-for-product
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup product-service.microservices.svc.cluster.local; do
                echo "Waiting for product-service..."
                sleep 2
              done
      containers:
        - name: gateway
          image: ghcr.io/kelysaina/gateway:latest
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: microservices
spec:
  selector:
    app: gateway
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30000
  type: NodePort
