version: "3.9"

services:
  auth-service:
    build: ./auth-service
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
