---
- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    mode: 0755

- name: Copy kubeconfig for user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    mode: 0644

- name: Install Flannel CNI
  become: true
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Get kubeadm join command
  command: kubeadm token create --print-join-command
  register: join_cmd

- name: Save join command to file
  copy:
    content: "{{ join_cmd.stdout }}"
    dest: /tmp/kubeadm_join.sh
