name: CI/CD

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: kelysaina

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/auth-service:latest ./auth-service
          docker push $REGISTRY/$IMAGE_OWNER/auth-service:latest

          docker build -t $REGISTRY/$IMAGE_OWNER/order-service:latest ./order-service
          docker push $REGISTRY/$IMAGE_OWNER/order-service:latest

          docker build -t $REGISTRY/$IMAGE_OWNER/product-service:latest ./product-service
          docker push $REGISTRY/$IMAGE_OWNER/product-service:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          npm test --prefix auth-service || true
          npm test --prefix order-service || true
          pytest product-service/tests || true

  deploy:
    runs-on: self-hosted # your master node runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
